[project]
name = "pkmtyping"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "jaraco-text>=4.0.0",
    "numpy>=2.1.1",
    "pygame>=2.6.0",
    "setuptools>=74.1.2",
]
